name: CVE Email Alerts

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hour

jobs:
  send-cve-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run alert script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python your_script.py
